apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose.exe convert
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: cs
  name: cs
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: cs
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose.exe convert
        kompose.version: 1.26.1 (a9d05d509)
      creationTimestamp: null
      labels:
        io.kompose.service: cs
    spec:
      containers:
        - image: cs
          name: cs
          imagePullPolicy: Never
          ports:
            - containerPort: 8087
            - containerPort: 8086
          resources: {}
          stdin: true
          tty: true
      restartPolicy: Always
status: {}
