apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose.exe convert
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: cs
  name: cs
spec:
  ports:
    - name: "8087"
      port: 8087
      targetPort: 8087
    - name: "8086"
      port: 8086
      targetPort: 8086
  selector:
    io.kompose.service: cs
#status:
#  loadBalancer: {}
