apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose.exe convert
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: hazelcast
  name: hazelcast
spec:
  ports:
    - name: "5701"
      port: 5701
      targetPort: 5701
    - name: "8088"
      port: 8088
      targetPort: 8080
  selector:
    io.kompose.service: hazelcast
#status:
#  loadBalancer: {}
